services:
  web:
    build:
      context: ./back-end-todo
    ports:
      - "4000:3000"
    secrets:
      - db_password
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: /run/secrets/db_password
    depends_on:
      - db
    networks:
      - bdd

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bdd

  secrets:
    db_password:
      external: true

  networks:
    bdd:

  volumes:
    db_data:
